# All-in-one continuous integration (CI) workflow.
# Runs on all platforms (Windows, macOS, and Linux)
# for all events (pull request, release, and schedule).

name: CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Synergy version number
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  schedule:
    - cron: "0 5 * * *" # 5am UTC

env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  SYNERGY_PRODUCT_NAME: ${{ vars.SYNERGY_PRODUCT_NAME }}
  SYNERGY_EDITION_TYPE: ${{ vars.SYNERGY_EDITION_TYPE }}
  SYNERGY_PACKAGE_PREFIX: ${{ vars.SYNERGY_PACKAGE_PREFIX }}
  SYNERGY_ENABLE_ACTIVATION: ${{ vars.SYNERGY_ENABLE_ACTIVATION }}
  PACKAGE_BUILD: ${{ !github.event.pull_request.draft }}
  PACKAGE_UPLOAD: ${{ !github.event.pull_request.draft }}

jobs:
  # Quality gate to allow PR merge, used in the branch protection rules.
  ci-passed:
    runs-on: ubuntu-latest
    needs: [windows, macos, linux]

    steps:
      - run: echo "âœ… CI passed" > $GITHUB_STEP_SUMMARY

  aws-s3-upload:
    runs-on: ubuntu-latest
    needs: [windows, macos, linux]
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'schedule' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version env var
        uses: ./.github/actions/get-version

      - name: Upload to AWS S3
        uses: ./.github/actions/dist-upload
        with:
          aws-s3-target-dir: ${{ vars.AWS_S3_UPLOAD_DIR }}
          aws-s3-package-version: ${{ env.SYNERGY_VERSION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  windows:
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.runs-on }}
    container: ${{ matrix.target.container }}
    timeout-minutes: 20

    strategy:
      # Normally, we want to fail fast, but in this case we shouldn't since one target may
      # fail due to transient issues unrelated to the build.
      fail-fast: false

      matrix:
        target:
          - name: windows-2022-x64
            runs-on: windows-2022-8-core-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache vcpkg dir
        uses: actions/cache@v4
        with:
          path: |
            vcpkg
            vcpkg_installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

      # Install Qt with an action instead of AQT, which seems broken on Windows CI.
      - name: Install Qt
        if: ${{runner.os == 'Windows'}}
        uses: jurplel/install-qt-action@v4
        with:
          dir: "C:"
          version: 6.7
          cache: true
          cache-key-prefix: windows-qt-6.7

      - name: Cache deps dir
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles('config.yaml') }}

      # This effectively runs `vcvarsall.bat`, etc. It's not actually installing
      # VC++ as that's already pre-installed on the Windows runner.
      - name: Setup VC++ environment
        uses: ilammy/msvc-dev-cmd@v1

      # Install Ninja with an action instead of using Chocolatey, as it's more
      # reliable and faster. The Ninja install action is pretty good as it
      # downloads directly from the `ninja-build` GitHub project releases.
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install dependencies
        env:
          VCPKG_ROOT: "" # Unset deliberately to suppress 'already installed' warning.
        run: python ./scripts/install_deps.py

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: |
          cmake -B build `
          --preset=windows-release `
          -DUSE_TOMLPLUSPLUS=OFF `
          -DUSE_CLI11=OFF `
          -DSYNERGY_VERSION_CHECK=${{ vars.SYNERGY_VERSION_CHECK }}

      - name: Build
        run: cmake --build build -j8

      - name: Tests
        uses: ./.github/actions/run-tests
        timeout-minutes: 2
        with:
          job: ${{ matrix.target.name }}
          bin-dir: build/bin

      - name: Package
        if: ${{ env.PACKAGE_BUILD == 'true' }}
        run: python ./scripts/package.py
        env:
          WINDOWS_PFX_CERTIFICATE: ${{ secrets.WINDOWS_PFX }}
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_PFX_PASS }}

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: "package-${{ env.SYNERGY_PACKAGE_PREFIX }}-${{ matrix.target.name }}"
          path: ./dist

  macos:
    name: ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.os }}
    timeout-minutes: ${{ matrix.target.timeout }}

    defaults:
      run:
        shell: ${{ matrix.target.shell }}

    strategy:
      # Normally, we want to fail fast, but in this case we shouldn't since one target may
      # fail due to transient issues unrelated to the build.
      fail-fast: false

      matrix:
        target:
          - name: "macos-14-arm64"
            timeout: 10
            os: "macos-14"
            arch: arm64
            shell: "/usr/bin/arch -arch arm64e /bin/bash --noprofile --norc -eo pipefail {0}"

          - name: ${{ 'macos-14-x64' }}
            timeout: 20
            os: ${{ 'macos-14-large' }}
            arch: x64
            shell: "bash"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache deps dir
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-deps-${{ hashFiles('config.yaml') }}

      - name: Install dependencies
        run: ./scripts/install_deps.py

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: |
          cmake -B build \
          --preset=macos-release \
          -DUSE_TOMLPLUSPLUS=OFF \
          -DUSE_CLI11=OFF \
          -DSYNERGY_VERSION_CHECK=${{ vars.SYNERGY_VERSION_CHECK }}

      - name: Build
        run: cmake --build build -j8

      - name: Tests
        uses: ./.github/actions/run-tests
        timeout-minutes: 2
        with:
          job: ${{ matrix.target.name }}
          bin-dir: build/bin

      - name: Package
        if: ${{ env.PACKAGE_BUILD == 'true' }}
        run: ./scripts/package.py
        env:
          APPLE_CODESIGN_ID: ${{ secrets.APPLE_CODESIGN_ID }}
          APPLE_P12_CERTIFICATE: ${{ secrets.APPLE_P12_CERTIFICATE }}
          APPLE_P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          APPLE_NOTARY_USER: ${{ secrets.APPLE_NOTARY_USER }}
          APPLE_NOTARY_PASSWORD: ${{ secrets.APPLE_NOTARY_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: "package-${{ env.SYNERGY_PACKAGE_PREFIX }}-${{ matrix.target.name }}"
          path: ./dist

  linux-matrix:
    runs-on: ubuntu-latest

    outputs:
      json-matrix: ${{ steps.get.outputs.json }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get JSON file
        id: get
        run: |
          json_file=".github/workflows/ci-linux.json"
          json=$(cat $json_file)
          echo "json=$(echo $json)" >> $GITHUB_OUTPUT

  linux:
    needs: linux-matrix
    name: linux-${{ matrix.distro.name }}
    runs-on: ${{ matrix.distro.runs-on }}
    container: ${{ matrix.distro.container }}
    timeout-minutes: 20

    strategy:
      # Normally, we want to fail fast, but in this case we shouldn't since one distro may
      # fail due to transient issues unrelated to the build.
      fail-fast: false
      matrix: ${{fromJson(needs.linux-matrix.outputs.json-matrix)}}

    steps:
      - name: Setup distro and deps
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run : |
          if [ "${{ matrix.distro.like }}" == "debian" ]; then
            apt update
            apt install -y git python3 python3-venv
          elif [ "${{ matrix.distro.like }}" == "fedora" ]; then
            dnf install -y git python3
          elif [ "${{ matrix.distro.like }}" == "suse" ]; then
            zypper refresh
            zypper install -y --force-resolution git python3
          elif [ "${{ matrix.distro.like }}" == "arch" ]; then
            pacman -Syu --noconfirm git python sudo
            useradd -m build
          else
            echo "Unknown: ${{ matrix.distro.like }}"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Config Git safe dir
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install dependencies
        run: ./scripts/install_deps.py ${{ matrix.distro.extra-dep-args }}
        env:
          # Prevent apt prompting for input.
          DEBIAN_FRONTEND: noninteractive

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Configure
        run: |
          cmake -B build \
          --preset=linux-release ${{ matrix.distro.extra-cmake-args }} \
          -DUSE_TOMLPLUSPLUS=OFF \
          -DUSE_CLI11=OFF \
          -DSYNERGY_VERSION_CHECK=${{ vars.SYNERGY_VERSION_CHECK }}

      - name: Build
        run: cmake --build build -j8

      - name: Tests
        uses: ./.github/actions/run-tests
        timeout-minutes: 2
        with:
          job: linux-${{ matrix.distro.name }}
          bin-dir: build/bin

      - name: Package
        if: ${{ env.PACKAGE_BUILD == 'true' }}
        env:
          LINUX_PACKAGE_USER: ${{ matrix.distro.package-user }}
        run: ./scripts/package.py

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: "package-${{ env.SYNERGY_PACKAGE_PREFIX }}-${{ matrix.distro.name }}"
          path: ./dist
